userTokenExpire=86400

[server]
baseUrl="http://127.0.0.1:3000"
port=8080

[database]
driver="mysql"
host="localhost"
user="root"
password="root"
db="celestial"
port=3306
prefix="t_"
showSql=true

[logger]
level="info"

[meilisearch]
host="http://localhost:7700"
apiKey="aaabbbcccdddeeefff"
index="celestial"

[onlyoffice]
secret="IVeIGPyPCikZUd3BLwEJ3begXNj2oZ5I"