name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # 编译前端
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18.15.0'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
          run_install: false
      - name: Install Dependency  # 安装依赖
        run: pnpm install
        working-directory: ./page/source
      - name: Build Page  # 编译前端页面
        run: pnpm build
        working-directory: ./page/source
      # 打包前端构建品, 打包到page/page.zip
      - name: Zip Page
        run: tar -zcvf page.tar.gz ./build/
        working-directory: ./page
      # 编译后端，根据goreleaser.yaml将后端打包到dist目录
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      # 安装upx
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          install-only: true
      # 使用goreleaser编译多系统多架构的二进制文件
      - name: Build Server
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --skip=validate,publish,sign
      # 发布到releases
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
            dist/metadata.json
            page/page.tar.gz
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
#        uses: marvinpinto/action-automatic-releases@latest
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          automatic_release_tag: 'latest'
#          files: |
#            dist/*.tar.gz
#            dist/*.zip
#            dist/checksums.txt
#            dist/metadata.json
#            page/page.tar.gz
