name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # 编译前端
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18.15.0'
      - name: Build Page
        run: |
          cd page/source
          npm install
          npm run build
      # 打包前端构建品, 打包到page/page.zip
      - name: Zip Page
        uses: thedoctor0/zip-release@latest
        with:
          type: 'tar'
          filename: 'page.zip'
          directory: 'page'
          path: 'build'
      # 编译后端，根据goreleaser.yaml将后端打包到dist目录
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - name: Build Server
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist --skip-validate --skip-publish --skip-sign
      # 发布到releases
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'latest'
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
            dist/metadata.json
            page/page.zip
